#'
#' Routine to create a model selection report
#'
#' @description Routine to create a PDF report of an automated logistic regression model selection.
#' From the output of csslr.model.selection a RMarkdown document is built in a temporary folder.
#' This document is rendered and a PDF is written into the current working directory
#' 
#' @param SelectionOutput Output list generated by csslr.model.selection
#' @param DT.data Data set containing the response variable and all independent variables
#' @param detailed If TRUE all models selection steps are reported in separate tables;
#' if FALSE only the leading and equivalent models are reported without details on the
#' selection algorithm
#' @export
csslr.utils.genreport <- function(SelectionOutput, DT.data, detailed = TRUE) {

  # Generate temp folder for saving files needed for report generation
  tmpDir <- paste0(normalizePath(tempdir()),'/')

  # Generate RMarkdown file
  rmdReport <- ''
  rmdReport <- paste0(rmdReport, '---\n')
  rmdReport <- paste0(rmdReport, 'title: "**CSSLR Model Selection Report**"\n')
  rmdReport <- paste0(rmdReport, 'date: "`r Sys.time()`"\n')
  rmdReport <- paste0(rmdReport, 'header-includes:\n')
  rmdReport <- paste0(rmdReport, ' - \\usepackage{longtable}\n')
  rmdReport <- paste0(rmdReport, 'output: pdf_document\n')
  rmdReport <- paste0(rmdReport, '---\n')
  rmdReport <- paste0(rmdReport, '\n# Selected Models\n\n')
  rmdReport <- paste0(rmdReport, 'In this section all statistically equivalent
                      models are displayed together with their summary statistics.
                      In the first part a table containing all equivalent models together
                      with AUC and MSE is displayed. After that the leading model(s) and
                      all equivalent models are presented.\n\n')

  rmdReport <- paste0(rmdReport, '\n## Overview of Selected Models\n\n')

  # Start with the header of the RMarkdown output
  rmdReport <- paste0(rmdReport, '```{r include = FALSE}\n')
  rmdReport <- paste0(rmdReport, 'library(data.table)\n')
  rmdReport <- paste0(rmdReport, 'library(xtable)\n')
  rmdReport <- paste0(rmdReport, 'filename <- "SelectionReport.RData"\n')
  rmdReport <- paste0(rmdReport, 'load(filename)\n')
  rmdReport <- paste0(rmdReport, '```\n\n')

  # Find the last EQUIVALENT report to be displayed
  foundStep <- ''
  for (theStep in names(SelectionOutput$SelectionReport)) {
    if ("EQUIVALENT" %in% names(SelectionOutput$SelectionReport[[theStep]]) == TRUE) {
      foundStep <- theStep
    }
  }
  rmdReport <- paste0(rmdReport, '```{r results="asis", echo=FALSE, warning=FALSE}\n')
  rmdReport <- paste0(rmdReport, 'displayTable <- sr[["',foundStep,'"]][["EQUIVALENT"]]\n')
  rmdReport <- paste0(rmdReport, 'displayTable <- displayTable[Decision != "Rejected"]\n')
  rmdReport <- paste0(rmdReport, 'oldNames <- names(displayTable)\n')
  rmdReport <- paste0(rmdReport, 'newNames <- c("Model","AUC","pAUC","MSE","pMSE","Decision")\n')
  rmdReport <- paste0(rmdReport, 'setnames(displayTable, oldNames, newNames)\n')
  rmdReport <- paste0(rmdReport, 'setorderv(displayTable, c("Decision","AUC"), order = c(-1,-1))\n')
  rmdReport <- paste0(rmdReport, 'equivTab <- xtable(displayTable, ',
                      'caption = "Final selection of equivalent models.", label = "step:final:equiv", ',
                      'digits = c(0, 0, 4, 1, 3, 1, 0), display=c("s", "s", "f", "e", "e", "e", "s"))\n')
  rmdReport <- paste0(rmdReport, 'align(equivTab) <- "lp{8cm}rrrrr"\n')
  rmdReport <- paste0(rmdReport, 'print(equivTab, comment=FALSE, tabular.environment = "longtable",
                        table.placement="ht!", include.rownames = F)\n')
  rmdReport <- paste0(rmdReport, '```\n\n\\clearpage\n\n')

  # Start with the header of the RMarkdown output
  rmdReport <- paste0(rmdReport, '```{r include = FALSE}\n')
  rmdReport <- paste0(rmdReport, 'library(data.table)\n')
  rmdReport <- paste0(rmdReport, 'library(xtable)\n')
  rmdReport <- paste0(rmdReport, 'filename <- "LeadingModels.RData"\n')
  rmdReport <- paste0(rmdReport, 'load(filename)\n')
  rmdReport <- paste0(rmdReport, '```\n\n')

  modelOutput <- list()
  allModels <- SelectionOutput$ModelsLeading
  rmdReport <- paste0(rmdReport, '\n## Leading Model(s)\n\n')
  for (i in 1:length(allModels)) {
    theModel <- allModels[i][[1]]
    modelResult <- csslr.model.analysis.lr(theModel, DT.data, lr=F, roc=F, ic=F, calib=F, quiet=T, dataValidation = F)
    # Next create the documentation for the model summary
    model.summary.xtable <- xtable(modelResult[['model.summary']])
    modelOutput[[paste0('summary',i)]] <- model.summary.xtable
    # RMarkdown chunk for the model summary
    modelName <- paste0('Leading Model ', i)
    referenceTag <- paste0('selectmodel', i)
    outputObjectName <- 'modelOutput'
    rmdReport <- paste0(rmdReport, '```{r results="asis", echo=FALSE, warning=FALSE}\n')
    rmdReport <- paste0(rmdReport, 'summaryName <- ', outputObjectName, '[["summary',i,'"]]\n')
    rmdReport <- paste0(rmdReport, 'summaryName$`Pr(>|z|)` <- format(summaryName$`Pr(>|z|)`, scientific = T, digits = 3)\n')
    rmdReport <- paste0(rmdReport, 'summaryName$`Pr(>|z|)` <- ifelse(as.numeric(summaryName$`Pr(>|z|)`) < 1.0e-10, "< 1.0e-10", summaryName$`Pr(>|z|)`)\n')
    rmdReport <- paste0(rmdReport, 'summaryTab <- xtable(summaryName, caption="Summary of ', modelName, '.", label = "tab:', referenceTag, ':leadsummary", ',
                        'digits = c(0, 3, 4, 2, 4), display=c("s", "f", "f", "f", "g"))\n')
    rmdReport <- paste0(rmdReport, 'align(summaryTab) <- "lrrrr"\n')
    rmdReport <- paste0(rmdReport, 'print(summaryTab, comment=FALSE, table.placement="ht!", include.rownames = T)\n')
    rmdReport <- paste0(rmdReport, '```\n')
  }
  rmdReport <- paste0(rmdReport, '\n\\clearpage\n\n')
  save(modelOutput, file = paste0(tmpDir, 'LeadingModels.RData'))

  removeIdx <- c()
  modelsEquivalent <- SelectionOutput$ModelsSelected
  modelsLeading <- SelectionOutput$ModelsLeading
  for (i in 1:length(modelsEquivalent)) {
    varNames <- all.vars(modelsEquivalent[[i]])
    for (j in 1:length(modelsLeading)) {
      leadingNames <- all.vars(modelsLeading[[j]])
      if (length(varNames) == length(leadingNames) & all(varNames %in% leadingNames)) {
        removeIdx <- c(removeIdx, i)
      }
    }
  }
  if (length(removeIdx) > 0) {
    removeIdx <- unique(removeIdx)
    modelsEquivalent <- modelsEquivalent[-removeIdx]
  }
  
  # Start with the header of the RMarkdown output
  rmdReport <- paste0(rmdReport, '```{r include = FALSE}\n')
  rmdReport <- paste0(rmdReport, 'library(data.table)\n')
  rmdReport <- paste0(rmdReport, 'library(xtable)\n')
  rmdReport <- paste0(rmdReport, 'filename <- "EquivalentModels.RData"\n')
  rmdReport <- paste0(rmdReport, 'load(filename)\n')
  rmdReport <- paste0(rmdReport, '```\n\n')

  modelEquivalent <- list()
  allModels <- modelsEquivalent
  rmdReport <- paste0(rmdReport, '\n## Equivalent Model(s)\n\n')
  for (i in 1:length(allModels)) {
    theModel <- allModels[i][[1]]
    modelResult <- csslr.model.analysis.lr(theModel, DT.data, lr=F, roc=F, ic=F, calib=F, quiet=T, dataValidation = F)
    # Next create the documentation for the model summary
    model.summary.xtable <- xtable(modelResult[['model.summary']])
    modelEquivalent[[paste0('summary',i)]] <- model.summary.xtable
    # RMarkdown chunk for the model summary
    modelName <- paste0('Equivalent Model ', i)
    referenceTag <- paste0('selectmodel', i)
    outputObjectName <- 'modelEquivalent'
    rmdReport <- paste0(rmdReport, '```{r results="asis", echo=FALSE, warning=FALSE}\n')
    rmdReport <- paste0(rmdReport, 'summaryName <- ', outputObjectName, '[["summary',i,'"]]\n')
    rmdReport <- paste0(rmdReport, 'summaryName$`Pr(>|z|)` <- format(summaryName$`Pr(>|z|)`, scientific = T, digits = 3)\n')
    rmdReport <- paste0(rmdReport, 'summaryName$`Pr(>|z|)` <- ifelse(as.numeric(summaryName$`Pr(>|z|)`) < 1.0e-10, "< 1.0e-10", summaryName$`Pr(>|z|)`)\n')
    rmdReport <- paste0(rmdReport, 'summaryTab <- xtable(summaryName, caption="Summary of ', modelName, '.", label = "tab:', referenceTag, ':equivsummary", ',
                        'digits = c(0, 3, 4, 2, 4), display=c("s", "f", "f", "f", "g"))\n')
    rmdReport <- paste0(rmdReport, 'align(summaryTab) <- "lrrrr"\n')
    rmdReport <- paste0(rmdReport, 'print(summaryTab, comment=FALSE, table.placement="ht!", include.rownames = T)\n')
    rmdReport <- paste0(rmdReport, '```\n')
  }
  rmdReport <- paste0(rmdReport, '\n\\clearpage\n\n')
  save(modelEquivalent, file = paste0(tmpDir, 'EquivalentModels.RData'))

  sr <- SelectionOutput$SelectionReport

  if (detailed == TRUE) {
    rmdReport <- paste0(rmdReport, '\n# Model Selection Report\n\n')
    rmdReport <- paste0(rmdReport, 'In this section all the steps are detailed
                      that allow a user to track the selection algorithm. In
                      particular, it is displayed which model was tested in which
                      step of the stepwise selection and what decision the
                      algorithm has made.\n\n')

    # Start with the header of the RMarkdown output
    rmdReport <- paste0(rmdReport, '```{r include = FALSE}\n')
    rmdReport <- paste0(rmdReport, 'library(data.table)\n')
    rmdReport <- paste0(rmdReport, 'library(xtable)\n')
    rmdReport <- paste0(rmdReport, 'filename <- "SelectionReport.RData"\n')
    rmdReport <- paste0(rmdReport, 'load(filename)\n')
    rmdReport <- paste0(rmdReport, '```\n\n')
    
    for (i in 1:length(sr)) {
      sr[[paste0('Step',i)]][['IMPROVED']] <- sr[[paste0('Step',i)]][['IMPROVED']][, c('AIC','BIC') := NULL]
      oldNames <- names(sr[[paste0('Step',i)]][['IMPROVED']])
      newNames <- c('Model','pCoeff','AUC','pAUC','MSE','pMSE','Decision')
      setnames(sr[[paste0('Step',i)]][['IMPROVED']], oldNames, newNames)
      rmdReport <- paste0(rmdReport, '\n## Model Selection Step ',i,'\n\n')
      # Table generation for the IMPROVED step
      rmdReport <- paste0(rmdReport, '```{r results="asis", echo=FALSE, warning=FALSE}\n')
      rmdReport <- paste0(rmdReport, 'impTab <- xtable(sr[["Step', i, '"]][["IMPROVED"]], ',
                          'caption = "Model selection Step ', i, ': Find IMPROVED models", label = "step:', i, ':improved", ',
                          'digits = c(0, 0, 1, 4, 1, 3, 1, 0), display=c("s", "s", "e", "f", "e", "e", "e", "s"))\n')
      rmdReport <- paste0(rmdReport, 'align(impTab) <- "lp{5cm}rrrrrr"\n')
      rmdReport <- paste0(rmdReport, 'print(impTab, comment=FALSE, tabular.environment = "longtable",
                        table.placement="ht!", include.rownames = F)\n')
      rmdReport <- paste0(rmdReport, '```\n\n\\clearpage\n\n')
      # Table generation for the TRIM step
      if ("TRIM" %in% names(sr[[paste0("Step",i)]]) == TRUE) {
        rmdReport <- paste0(rmdReport, '```{r results="asis", echo=FALSE, warning=FALSE}\n')
        rmdReport <- paste0(rmdReport, 'trimTab <- xtable(sr[["Step', i, '"]][["TRIM"]], ',
                            'caption = "Model selection Step ', i, ': Outcome of the TRIM process", label = "step:', i, ':trim", ',
                            'digits = c(0, 0, 0), display=c("s", "s", "s"))\n')
        rmdReport <- paste0(rmdReport, 'align(trimTab) <- "lp{12cm}r"\n')
        rmdReport <- paste0(rmdReport, 'print(trimTab, comment=FALSE, tabular.environment = "longtable",
                        table.placement="ht!", include.rownames = F)\n')
        rmdReport <- paste0(rmdReport, '```\n\n\\clearpage\n\n')
      }
      # Table generation for the TRIM step
      if ("LEADING" %in% names(sr[[paste0("Step",i)]]) == TRUE) {
        rmdReport <- paste0(rmdReport, '```{r results="asis", echo=FALSE, warning=FALSE}\n')
        rmdReport <- paste0(rmdReport, 'leadTab <- xtable(sr[["Step', i, '"]][["LEADING"]], ',
                            'caption = "Model selection Step ', i, ': Outcome of finding LEADING models", label = "step:', i, ':lead", ',
                            'digits = c(0, 0, 4, 4, 0), display=c("s", "s", "f", "f", "s"))\n')
        rmdReport <- paste0(rmdReport, 'align(leadTab) <- "lp{10cm}rrr"\n')
        rmdReport <- paste0(rmdReport, 'print(leadTab, comment=FALSE, tabular.environment = "longtable",
                        table.placement="ht!", include.rownames = F)\n')
        rmdReport <- paste0(rmdReport, '```\n\n\\clearpage\n\n')
      }
      if ("EQUIVALENT" %in% names(sr[[paste0("Step",i)]]) == TRUE) {
        oldNames <- names(sr[[paste0('Step',i)]][['EQUIVALENT']])
        newNames <- c('Model','AUC','pAUC','MSE','pMSE','Decision')
        setnames(sr[[paste0('Step',i)]][['EQUIVALENT']], oldNames, newNames)
        rmdReport <- paste0(rmdReport, '```{r results="asis", echo=FALSE, warning=FALSE}\n')
        rmdReport <- paste0(rmdReport, 'equivTab <- xtable(sr[["Step', i, '"]][["EQUIVALENT"]], ',
                            'caption = "Model selection Step ', i, ': Outcome of finding EQUIVALENT models", label = "step:', i, ':equiv", ',
                            'digits = c(0, 0, 4, 1, 3, 1, 0), display=c("s", "s", "f", "e", "e", "e", "s"))\n')
        rmdReport <- paste0(rmdReport, 'align(equivTab) <- "lp{8cm}rrrrr"\n')
        rmdReport <- paste0(rmdReport, 'print(equivTab, comment=FALSE, tabular.environment = "longtable",
                        table.placement="ht!", include.rownames = F)\n')
        rmdReport <- paste0(rmdReport, '```\n\n\\clearpage\n\n')
      }
    }
  }

  save(sr, file = paste0(tmpDir, 'SelectionReport.RData'))

  # Save file in temp folder and render PDF
  cat(rmdReport, file = paste0(tmpDir, 'CSSLR_Report.Rmd'))
  render(input = paste0(tmpDir, 'CSSLR_Report.Rmd'), output_dir = getwd())
}
